[package]
name = "day_3"
version = "0.1.0"
authors = ["MajorX234 <majorx234@googlemail.com>"]
edition = "2021"

[[bin]]
name = "day_3_task_1"
path = "src/main.rs"

[dependencies]
day_1 = {path = "../day_1", version = "0.1.0"}
nom = {version = "7.1.1"}
